packages:
  - apps/*
  - packages/*
catalog:
  'sst': '^3.16.0'
  'typescript': '^5.4.5'
  'gql.tada': '^1.7.5'
  'graphql': '^16.8.1'
  '@types/node': '^20'
  '@graphql-typed-document-node/core': '^3.2.0'
  '@0no-co/graphqlsp': '^1.12.5'
  'graphql-modules': '^2.3.0'
  '@trpc/client': '11.0.0-rc.396'
  '@trpc/react-query': '11.0.0-rc.396'
  '@trpc/server': '11.0.0-rc.396'
  'dayjs': '^1.11.13'
  'tailwindcss': '^3.4.17'
  'react': '^18'
  'react-dom': '^18.3.1'
  '@types/react': '^18'
  '@types/react-dom': '^18'
