packages:
  - apps/*
  - packages/*

catalog:
  '@0no-co/graphqlsp': ^1.15.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@trpc/client': ^11.5.1
  '@trpc/react-query': ^11.5.1
  '@trpc/server': ^11.5.1
  '@types/node': ^20.19.13
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  dayjs: ^1.11.18
  gql.tada: ^1.8.13
  graphql: ^16.11.0
  graphql-modules: ^2.4.0
  react: ^19.1.1
  react-dom: ^19.1.1
  sst: ^3.17.12
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
