/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Client": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SecretBrevoAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretDomainARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretPasswordlessSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretResendAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretUserAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Server": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}