service: epc-next
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - s3:*
          Resource:
            - '*'
  environment:
    # VARIABLE: ${ssm:/project--variable}
    USER_AUTH_SECRET: ${ssm:/epc--user-auth-secret}
    PASSWORDLESS_SECRET: ${ssm:/epc--passwordless-secret}
    BREVO_API_KEY: ${ssm:/epc--brevo-api-key}
    RESEND_API_KEY: ${ssm:/epc--resend-api-key}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

custom:
  esbuild:
    # plugins: esPlugins.js

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-ignore
