service: epc-next
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  profile: elmpoint-aws
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - s3:*
          Resource:
            - '*'
  environment:
    # VARIABLE: ${ssm:/project--variable}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

custom:
  esbuild:
    # plugins: esPlugins.js

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-ignore
