# run as a check on every pull request
name: test next.js build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      # prepare codebase
      - uses: actions/checkout@v4.1.6

      # install libraries
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - uses: actions/setup-node@v4.0.2
        with:
          cache: 'pnpm'
      - name: authenticate tiptap
        env:
          TIPTAP_KEY: ${{ secrets.TIPTAP_KEY }}
        run: |
          npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
          npm config set "//registry.tiptap.dev/:_authToken" $TIPTAP_KEY
      - run: pnpm install
      # build
      - name: build
        run: |
          pnpm build
