# run as a check on every pull request
name: test next.js build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      # prepare codebase
      - uses: actions/checkout@v4

      - name: turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # install libraries
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: authenticate tiptap
        env:
          TIPTAP_KEY: ${{ secrets.TIPTAP_KEY }}
        run: |
          npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
          npm config set "//registry.tiptap.dev/:_authToken" $TIPTAP_KEY
      - run: pnpm install
      # tests
      - name: check types
        run: |
          pnpm test
      - name: full next build
        if: github.event.pull_request.draft == false
        run: |
          pnpm build
