name: deploy project
on:
  workflow_dispatch: # manual deploy
  push:
    tags:
      - '*'
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      # prepare codebase
      - uses: actions/checkout@v4

      # install libraries
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: authenticate tiptap
        env:
          TIPTAP_KEY: ${{ secrets.TIPTAP_KEY }}
        run: |
          npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
          npm config set "//registry.tiptap.dev/:_authToken" $TIPTAP_KEY
      - run: pnpm install

        # deploy
      - name: deploy
        run: |
          pnpm push --stage=production
