name: deploy ion-migrate
on:
  push:
    branches:
      - ion-migrate
jobs:
  deploy-client:
    uses: './.github/workflows/deploy_client.yml'
    secrets: inherit
    with:
      stage: production
  deploy-server:
    uses: './.github/workflows/deploy_server.yml'
    secrets: inherit
